### ISSUE TITLE
got error using pycharm with python3.7 venv

### ISSUE THREAD

**Issue by aaron111com** [salimane/rediscluster-py#14]
Collecting rediscluster
  Using cached https://files.pythonhosted.org/packages/0a/2c/0f2ab19a4f20ea7bd2dbb4032fc332894feabdb0346353fbd9cbdb0c152d/rediscluster-0.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mh/j51d3djx15zb1n2xdpgt7y7m0000gn/T/pycharm-packaging/rediscluster/setup.py", line 2, in <module>
        from rediscluster import __version__
      File "/private/var/folders/mh/j51d3djx15zb1n2xdpgt7y7m0000gn/T/pycharm-packaging/rediscluster/rediscluster/__init__.py", line 12, in <module>
        from rediscluster.cluster_client import StrictRedisCluster
      File "/private/var/folders/mh/j51d3djx15zb1n2xdpgt7y7m0000gn/T/pycharm-packaging/rediscluster/rediscluster/cluster_client.py", line 5, in <module>
        from redis._compat import (
    ImportError: cannot import name 'b' from 'redis._compat' (/Users/apple/PycharmProjects/op_tool/venv/lib/python3.7/site-packages/redis/_compat.py)
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mh/j51d3djx15zb1n2xdpgt7y7m0000gn/T/pycharm-packaging/rediscluster/

**Comment by salimane** [comment]
@aaron111com this package has been deprecated in favor of the official redis library. Please upgrade to the official library.
