### ISSUE TITLE
cannot install using pip in python3.6

### ISSUE THREAD

**Issue by expwdx** [salimane/rediscluster-py#17]
I cannot install it success in python3.6.5. Is it not support python3.6 ?

```
(smartsys_env) ➜  smartsys git:(dev) ✗ pip install rediscluster -i https://pypi.python.org/simple
Looking in indexes: https://pypi.python.org/simple
Collecting rediscluster
  Downloading rediscluster-0.5.3.tar.gz (9.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/marco/.pyenv/versions/3.6.5/envs/smartsys_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fdfrpoe5/rediscluster/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fdfrpoe5/rediscluster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z72djrhh
         cwd: /tmp/pip-install-fdfrpoe5/rediscluster/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fdfrpoe5/rediscluster/setup.py", line 2, in <module>
        from rediscluster import __version__
      File "/tmp/pip-install-fdfrpoe5/rediscluster/rediscluster/__init__.py", line 12, in <module>
        from rediscluster.cluster_client import StrictRedisCluster
      File "/tmp/pip-install-fdfrpoe5/rediscluster/rediscluster/cluster_client.py", line 5, in <module>
        from redis._compat import (
    ImportError: cannot import name 'dictkeys'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(smartsys_env) ➜  smartsys git:(dev) ✗ pip install rediscluster                                  
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting rediscluster
  Using cached https://mirrors.aliyun.com/pypi/packages/0a/2c/0f2ab19a4f20ea7bd2dbb4032fc332894feabdb0346353fbd9cbdb0c152d/rediscluster-0.5.3.tar.gz (9.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/marco/.pyenv/versions/3.6.5/envs/smartsys_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iyqnhgz7/rediscluster/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iyqnhgz7/rediscluster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-etk4c5bu
         cwd: /tmp/pip-install-iyqnhgz7/rediscluster/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-iyqnhgz7/rediscluster/setup.py", line 2, in <module>
        from rediscluster import __version__
      File "/tmp/pip-install-iyqnhgz7/rediscluster/rediscluster/__init__.py", line 12, in <module>
        from rediscluster.cluster_client import StrictRedisCluster
      File "/tmp/pip-install-iyqnhgz7/rediscluster/rediscluster/cluster_client.py", line 5, in <module>
        from redis._compat import (
    ImportError: cannot import name 'dictkeys'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by salimane** [comment]
no this package is deprecated. Please use the official redis client

**Comment by DachuanZhao** [comment]
> no this package is deprecated. Please use the official redis client

Could you please give a [redirect link](https://pypi.org/project/redis-py-cluster/) in the [pypi document](https://pypi.org/project/rediscluster/) since this package is deprecated.
