### ISSUE TITLE
pip install raises error

### ISSUE THREAD

**Issue by DachuanZhao** [salimane/rediscluster-py#19]
python version : 3.7

```
    ERROR: Command errored out with exit status 1:
     command: /home/zhaodachuan/anaconda3/envs/hx_ranking_engine/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h284g8yq/rediscluster/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h284g8yq/rediscluster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-oc5tmmnm
         cwd: /tmp/pip-install-h284g8yq/rediscluster/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h284g8yq/rediscluster/setup.py", line 2, in <module>
        from rediscluster import __version__
      File "/tmp/pip-install-h284g8yq/rediscluster/rediscluster/__init__.py", line 12, in <module>
        from rediscluster.cluster_client import StrictRedisCluster
      File "/tmp/pip-install-h284g8yq/rediscluster/rediscluster/cluster_client.py", line 5, in <module>
        from redis._compat import (
    ImportError: cannot import name 'b'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by salimane** [comment]
This repo is deprecated. Please use the official Redis library.
